#!/usr/bin/env python3

import argparse
import sys
from lxml import html

from backend.hidmet import get_hidmet_weather_report_page, parse_date_from_hidmet_dom_tree, parse_reports
from frontend.terminal import get_ascii_art_cond, render_tables, output_tables


EXIT_SUCCESS = 0
EXIT_NO_KNOWN_STATIONS = 1
EXIT_NETWORK_ERROR = 2

STATIONS = {
    'pa': 'Палић',
    'so': 'Сомбор',
    'ns': 'Нови Сад',
    'bk': 'Б. Карловац',
    'lo': 'Лозница',
    'sm': 'С. Митровица',
    'va': 'Ваљево',
    'bg': 'Београд',
    'kg': 'Крагујевац',
    'sp': 'С. Паланка',
    'vg': 'В. Градиште',
    'cv': 'Црни Врх',
    'ne': 'Неготин',
    'zla': 'Златибор',
    'sj': 'Сјеница',
    'po': 'Пожега',
    'kv': 'Краљево',
    'kop': 'Копаоник',
    'ku': 'Куршумлија',
    'cu': 'Ћуприја',
    'ni': 'Ниш',
    'le': 'Лесковац',
    'za': 'Зајечар',
    'di': 'Димитровград'
}


def get_stations_by_abbrs(abbrs):
    return list(map(lambda x: STATIONS[x], abbrs))


def parse_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument("-l", "--list",
                        help="list all weather stations",
                        action="store_true")
    parser.add_argument("-a", "--all",
                        help="show weather reports from all stations",
                        action="store_true")
    parser.add_argument('station', nargs='*', default=['bg'],
                        help='weather station abbreviation')
    args = parser.parse_args()

    if args.list:
        for abbr in STATIONS:
            print(f"{abbr}\t%s" % STATIONS[abbr])
        sys.exit(EXIT_SUCCESS)

    abbrs = []
    for abbr in args.station:
        if abbr in STATIONS:
            abbrs.append(abbr)
        else:
            print("Unknown weather station: %s" % abbr, file=sys.stderr)
    if len(abbrs) == 0:
        sys.exit(EXIT_NO_KNOWN_STATIONS)

    station_names = STATIONS.values() if args.all \
        else get_stations_by_abbrs(abbrs)
    return station_names


station_names = parse_arguments()

# get weather reports (backend)
try:
    hidmet_page = get_hidmet_weather_report_page()
except Exception:
    print("Failed to get web page:", sys.exc_info()[1], file=sys.stderr)
    sys.exit(EXIT_NETWORK_ERROR)

hidmet_dom_tree = html.fromstring(hidmet_page.content)
date_line = parse_date_from_hidmet_dom_tree(hidmet_dom_tree)
reports = parse_reports(hidmet_dom_tree, station_names)

# render and output weather reports (frontend)
tables = render_tables(reports)
print('Подаци са главних метеоролошких станица')
print(date_line)
output_tables(tables)
