#!/usr/bin/env python3

import argparse
import sys

import backend.hidmet
import backend.metar
import frontend.terminal


EXIT_SUCCESS = 0
EXIT_UNKNOWN_BACKEND = 1


def parse_arguments():
    parser = argparse.ArgumentParser(prog='rhmz')
    subparsers = parser.add_subparsers(help='backend selection')

    parser_hidmet = subparsers.add_parser('hidmet', help='hidmet backend')
    parser_hidmet.set_defaults(func=backend.hidmet.parse_args)
    parser_hidmet.add_argument("-l", "--list",
                               help="list all weather stations",
                               action="store_true")
    parser_hidmet.add_argument("-a", "--all",
                               help="show weather reports from all stations",
                               action="store_true")
    parser_hidmet.add_argument('station', nargs='*', default=['bg'],
                               help='weather station abbreviation')

    parser_metar = subparsers.add_parser('metar', help='metar backend')
    parser_metar.set_defaults(func=backend.metar.parse_args)
    parser_metar.add_argument("-l", "--list",
                              help="list all weather stations",
                              action="store_true")
    parser_metar.add_argument("-a", "--all",
                              help="show weather reports from all stations",
                              action="store_true")
    parser_metar.add_argument('station', nargs='*', default=[],
                              help='weather station IATA id')

    args = parser.parse_args()

    return args.func(args) if 'func' in args \
        else ('hidmet', backend.hidmet.get_stations_by_abbrs(['bg']))


selected_backend, stations = parse_arguments()

try:
    fetch_reports = getattr(sys.modules['backend.' + selected_backend], 'fetch')
except Exception:
    print("Cannot load backend: %s" % selected_backend, file=sys.stderr)
    print(sys.exc_info(), file=sys.stderr)
    sys.exit(EXIT_UNKNOWN_BACKEND)

reports, header = fetch_reports(stations)

frontend.terminal.render_and_output(reports, header)
